'use client'

import { useEffect, useState } from 'react'
import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { Document as WordDocument, Packer, Paragraph, TextRun } from 'docx'
import { createClient } from '@/lib/supabase/client'
import PageHeader from '@/components/PageHeader'
import { logActivity } from '@/lib/activity'

type WorkspaceDoc = { id: string; title: string; content: Record<string, unknown>; author_id: string; status: 'draft' | 'final'; updated_at: string }
type Comment = { id: string; document_id: string; parent_id: string | null; body: string; created_at: string; profiles?: { full_name: string } }
type Task = { id: string; title: string; description: string | null; assignee_label: string | null; due_date: string | null; status: string; linked_doc_id: string | null }

function RichEditor({ documentId, value, onChange }: { documentId: string; value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void }) {
  const editor = useEditor({ extensions: [StarterKit], content: value, editorProps: { attributes: { class: 'min-h-64 px-4 py-3 outline-none prose prose-sm max-w-none' } }, onUpdate: ({ editor }) => onChange(editor.getJSON()) })
  useEffect(() => { if (editor) editor.commands.setContent(value, { emitUpdate: false }) }, [editor, documentId])
  if (!editor) return <div className="min-h-64 p-4 text-sm text-muted">Loading editor…</div>
  return <><div className="flex gap-2 border-b border-border p-2"><button type="button" onClick={() => editor.chain().focus().toggleBold().run()} className={`rounded px-2 py-1 text-sm ${editor.isActive('bold') ? 'bg-warm' : ''}`}>Bold</button><button type="button" onClick={() => editor.chain().focus().toggleBulletList().run()} className={`rounded px-2 py-1 text-sm ${editor.isActive('bulletList') ? 'bg-warm' : ''}`}>List</button><button type="button" onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()} className={`rounded px-2 py-1 text-sm ${editor.isActive('heading') ? 'bg-warm' : ''}`}>Heading</button></div><EditorContent editor={editor} /></>
}

function textFromContent(node: any): string {
  if (!node) return ''; if (node.type === 'text') return node.text || ''; return (node.content || []).map(textFromContent).join(node.type === 'paragraph' ? '\n' : '')
}

export default function WorkspacePage() {
  const supabase = createClient(); const [docs, setDocs] = useState<WorkspaceDoc[]>([]); const [selected, setSelected] = useState<WorkspaceDoc | null>(null); const [content, setContent] = useState<Record<string, unknown>>({ type: 'doc', content: [] }); const [comments, setComments] = useState<Comment[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [comment, setComment] = useState(''); const [taskTitle, setTaskTitle] = useState(''); const [taskDue, setTaskDue] = useState(''); const [taskAssignee, setTaskAssignee] = useState('Volunteer team'); const [role, setRole] = useState(''); const [error, setError] = useState('');
  const canManageTasks = ['admin', 'manager'].includes(role)
  const load = async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const [{ data: docsData, error: docsError }, { data: tasksData }, { data: profile }] = await Promise.all([supabase.from('workspace_docs').select('*').order('updated_at', { ascending: false }), supabase.from('tasks').select('*').order('due_date', { ascending: true }), supabase.from('profiles').select('role').eq('id', user.id).single()]); if (docsError) setError(docsError.message); else { setDocs(docsData || []); if (!selected && docsData?.[0]) openDoc(docsData[0]) } setTasks(tasksData || []); setRole(profile?.role || '') }
  const loadComments = async (documentId: string) => { const { data, error } = await supabase.from('workspace_comments').select('*, profiles(full_name)').eq('document_id', documentId).order('created_at'); if (error) setError(error.message); else setComments(data || []) }
  const openDoc = (doc: WorkspaceDoc) => { setSelected(doc); setContent(doc.content || { type: 'doc', content: [] }); loadComments(doc.id) }
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load()
  }, [])
  useEffect(() => { if (!selected) return; const channel = supabase.channel(`workspace-comments-${selected.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'workspace_comments', filter: `document_id=eq.${selected.id}` }, () => loadComments(selected.id)).subscribe(); return () => { supabase.removeChannel(channel) } }, [selected?.id])
  const createDoc = async () => { const title = window.prompt('Document title'); if (!title?.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const initial = { type: 'doc', content: [] }; const { data, error } = await supabase.from('workspace_docs').insert({ title: title.trim(), content: initial, author_id: user.id }).select().single(); if (error || !data) setError(error?.message || 'Unable to create document'); else { await logActivity('workspace.document.create', 'workspace_doc', data.id, { title: data.title }); await load(); openDoc(data) } }
  const saveDoc = async () => { if (!selected) return; const { error } = await supabase.from('workspace_docs').update({ content, updated_at: new Date().toISOString() }).eq('id', selected.id); if (error) setError(error.message); else { await logActivity('workspace.document.update', 'workspace_doc', selected.id, { title: selected.title }); await load() } }
  const exportDoc = async () => { if (!selected) return; const word = new WordDocument({ sections: [{ children: [new Paragraph({ children: [new TextRun({ text: selected.title, bold: true, size: 32 })] }), ...textFromContent(content).split('\n').filter(Boolean).map(text => new Paragraph(text))] }] }); const blob = await Packer.toBlob(word); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${selected.title.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'workspace-document'}.docx`; link.click(); URL.revokeObjectURL(link.href); await logActivity('workspace.document.export', 'workspace_doc', selected.id, { title: selected.title }) }
  const addComment = async (e: React.FormEvent) => { e.preventDefault(); if (!selected || !comment.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from('workspace_comments').insert({ document_id: selected.id, body: comment.trim(), author_id: user.id }); if (error) setError(error.message); else { setComment(''); await logActivity('workspace.comment.create', 'workspace_doc', selected.id) } }
  const addTask = async (e: React.FormEvent) => { e.preventDefault(); if (!taskTitle.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from('tasks').insert({ title: taskTitle.trim(), assignee_label: taskAssignee.trim() || 'Volunteer team', due_date: taskDue || null, linked_doc_id: selected?.id || null, created_by: user.id }); if (error) setError(error.message); else { setTaskTitle(''); setTaskDue(''); load(); await logActivity('task.create', 'task', undefined, { title: taskTitle, assignee: taskAssignee }) } }
  const setTaskStatus = async (task: Task, status: string) => { const { error } = await supabase.from('tasks').update({ status }).eq('id', task.id); if (error) setError(error.message); else load() }
  return <div><PageHeader title="Workspace" description="Draft reports, keep the discussion beside the work, and turn action items into tasks." action={<button onClick={createDoc} className="btn-primary !px-4 !py-2">New document</button>} />
    {error && <p className="mb-4 rounded-lg bg-rust/10 p-3 text-sm text-rust">{error}</p>}
    <div className="grid gap-6 lg:grid-cols-[15rem_1fr]">
      <aside className="rounded-xl border border-border bg-cream p-3"><h2 className="px-2 pb-2 text-sm font-semibold text-ink">Documents</h2>{docs.length === 0 && <p className="px-2 text-sm text-muted">Create the first report or meeting note.</p>}{docs.map(doc => <button key={doc.id} onClick={() => openDoc(doc)} className={`mb-1 w-full rounded-lg px-3 py-2 text-left text-sm ${selected?.id === doc.id ? 'bg-warm text-purple' : 'hover:bg-warm/50'}`}><span className="block truncate font-medium">{doc.title}</span><span className="text-xs text-muted">{doc.status} · {new Date(doc.updated_at).toLocaleDateString()}</span></button>)}</aside>
      <section className="space-y-6">{selected ? <><div className="overflow-hidden rounded-xl border border-border bg-cream"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div><h2 className="font-semibold text-ink">{selected.title}</h2><p className="text-xs text-muted">{selected.status}</p></div><div className="flex gap-2"><button onClick={saveDoc} className="rounded-lg bg-purple px-3 py-2 text-sm font-semibold text-white">Save</button><button onClick={exportDoc} className="rounded-lg border border-border px-3 py-2 text-sm font-semibold text-ink">Download Word</button></div></div><RichEditor documentId={selected.id} value={content} onChange={setContent} /></div>
        <div className="card"><h2 className="font-semibold text-ink">Comments</h2><div className="mt-3 space-y-3">{comments.map(item => <div key={item.id} className="rounded-lg bg-warm/50 p-3 text-sm"><p>{item.body}</p><p className="mt-1 text-xs text-muted">{item.profiles?.full_name || 'Team member'} · {new Date(item.created_at).toLocaleString()}</p></div>)}</div><form onSubmit={addComment} className="mt-4 flex gap-2"><input value={comment} onChange={e => setComment(e.target.value)} required maxLength={4000} placeholder="Add a comment" className="min-w-0 flex-1 rounded-lg border border-border px-3 py-2 text-sm" /><button className="rounded-lg bg-gold px-3 py-2 text-sm font-semibold text-white">Post</button></form></div>
      </> : <div className="card text-muted">Select a document or create one to start.</div>}
      <div className="card"><h2 className="font-semibold text-ink">Tasks</h2>{canManageTasks && <form onSubmit={addTask} className="mt-3 grid gap-2 md:grid-cols-4"><input value={taskTitle} onChange={e => setTaskTitle(e.target.value)} required placeholder="Task title" className="rounded-lg border border-border px-3 py-2 text-sm" /><input value={taskAssignee} onChange={e => setTaskAssignee(e.target.value)} placeholder="Assignee or Volunteer team" className="rounded-lg border border-border px-3 py-2 text-sm" /><input type="date" value={taskDue} onChange={e => setTaskDue(e.target.value)} className="rounded-lg border border-border px-3 py-2 text-sm" /><button className="rounded-lg bg-purple px-3 py-2 text-sm font-semibold text-white">Add task</button></form>}<div className="mt-4 space-y-2">{tasks.map(task => <div key={task.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-warm/50 p-3 text-sm"><div><p className="font-medium text-ink">{task.title}</p><p className="text-xs text-muted">{task.assignee_label || 'Unassigned'}{task.due_date ? ` · due ${task.due_date}` : ''}</p></div>{canManageTasks ? <select value={task.status} onChange={e => setTaskStatus(task, e.target.value)} className="rounded border border-border bg-cream px-2 py-1 text-xs"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select> : <span className="text-xs text-muted">{task.status.replace('_', ' ')}</span>}</div>)}{tasks.length === 0 && <p className="text-sm text-muted">No tasks yet.</p>}</div></div></section>
    </div>
  </div>
}
